# Generated by Django 5.1.1 on 2024-10-22 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='sell', max_length=4)),
                ('crypto_currency', models.CharField(choices=[('XMR', 'Monero')], default='XMR', max_length=3)),
                ('fiat_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('CHF', 'Swiss Franc'), ('RUB', 'Russian Ruble'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3)),
                ('price', models.DecimalField(decimal_places=8, default=2, max_digits=20)),
                ('min_amount', models.DecimalField(decimal_places=2, default=10, max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=20)),
                ('payment_methods', models.CharField(choices=[('SEPA', 'SEPA'), ('INSTANT SEPA', 'Instant SEPA'), ('BANK TRANSFER', 'Bank Transfer'), ('DEBIT CARD', 'Debit Card'), ('VISA/MASTERCARD', 'Visa/MasterCard'), ('MIR', 'MIR'), ('PAYPAL', 'PayPal'), ('REVOLUT', 'Revolut'), ('ALIPAY', 'Alipay'), ('LYDIA', 'Lydia'), ('WECHAT', 'WeChat'), ('GIFT CARD', 'Gift Card'), ('CASH BY MAIL', 'Cash by Mail'), ('CASH IN HAND', 'Cash in Hand'), ('BTC', 'Bitcoin'), ('CRYPTOCURRENCY', 'Cryptocurrency'), ('GOODS', 'Goods'), ('OTHER', 'Other')], default='BANK TRANSFER', max_length=255)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='Anywhere', max_length=255, null=True)),
                ('escrow_wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('escrow_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dynamic_price', models.BooleanField(default=False)),
                ('dynamic_price_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage adjustment (-15% to 15%)', max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
