# Generated by Django 5.1.1 on 2024-10-22 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_room', 'In Room'), ('closed', 'Closed')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('canceled', 'Transaction Canceled'), ('validated', 'Escrow Released'), ('no_action', 'No Action Taken')], default='no_action', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('support_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ChatArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_data', models.TextField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportrequest')),
            ],
        ),
    ]
