# Generated by Django 5.1 on 2024-08-14 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 18, 55, 19, 989043, tzinfo=datetime.timezone.utc)),
        ),
    ]
