# Generated by Django 5.1.1 on 2024-10-24 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 16, 48, 4, 3014, tzinfo=datetime.timezone.utc)),
        ),
    ]
