# Generated by Django 5.1.1 on 2024-10-24 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 16, 57, 27, 698372, tzinfo=datetime.timezone.utc)),
        ),
    ]
