# Generated by Django 5.1.1 on 2024-10-25 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 25, 15, 49, 59, 645254, tzinfo=datetime.timezone.utc)),
        ),
    ]
