# Generated by Django 5.1.1 on 2024-10-22 10:44

import django.db.models.deletion
import monero_app.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneroRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('inverse_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XmrWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', monero_app.models.EncryptedField(max_length=95, unique=True)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20)),
                ('wallet_type', models.CharField(choices=[('main', 'Main'), ('fee', 'Fee')], default='main', max_length=10)),
                ('wallet_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XmrSubaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', monero_app.models.EncryptedField(max_length=95, unique=True)),
                ('wallet_type', models.CharField(choices=[('user', 'User'), ('fee', 'Fee'), ('escrow', 'Escrow')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoneroTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', monero_app.models.EncryptedField(max_length=95, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], max_length=20)),
                ('confirmations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_outgoing', models.BooleanField(default=False)),
                ('destination_address', models.CharField(blank=True, max_length=95, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monero_app.xmrwallet')),
            ],
        ),
    ]
